### ISSUE TITLE
Remove anchor tag wrapped around image in the-basics/html/html-tags.html

### ISSUE THREAD

**Issue by jsnhall** [meghall/the-basics#2]
Unnecessary anchor tag wrapped around image element. Remove or add href to anchor.

`<a><img src="https://i.dailymail.co.uk/i/pix/2015/12/22/23/2F93D1CA00000578-0-image-a-10_1450825493645.jpg" alt="baby penguin"></a>
`

**Comment by meghall** [comment]
Added href to anchor element
